version: "3"

tasks:
  run:
    summary: Serve the blockchain using Ignite
    cmds:
      - docker-compose up
    silent: true

  build:
    cmds:
      - go build -o happendbd cmd/happendbd/*
    silent: false

  test:
    cmds:
      - go test ./... -cover -v